name: Latest virgool activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-virgool:
    name: Update this repo's README with latest activity from virgool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "VIRGOOL"
          commit_message: "Updated readme with the latest virgool data"
          feed_list: "https://virgool.io/feed/@m.arbabzi"